### ISSUE TITLE
Support Inline Math Formula

### ISSUE THREAD

**Issue by NYH-Dolphin** [526avijitgupta/gokarna#101]
Hi~ Nice to meet you again~

Actually, I know your websites use KaTeX to support the math formula.
However, I find that your web page just support block formula. Actually, there are lot's of cases that you need to express your statement by combining sentences with formula.

I wish you can add this function to gokarna to make it more flexible~
Here are some articles you can refer to~
https://mertbakir.gitlab.io/hugo/math-typesetting-in-hugo/
https://katex.org/docs/supported.html#line-breaks

Wish to hear from your reply~

**Comment by yashmehrotra** [comment]
Hi @NYH-Dolphin,

Can you send an example of what works, what doesn't & how to reproduce it ?

**Comment by NYH-Dolphin** [comment]
What I mean is that, if you type
Hi this is inline formula `$2x^2 + 1$`
![image](https://user-images.githubusercontent.com/60838786/175459844-c15e814f-5864-4d19-8bc7-fd93cb6e6d0c.png)
It should display a inline mathmetical formula instead of $(dollor) symbol and without any mathmetical formula~

**Comment by realansgar** [comment]
Adding this snippet taken from the [katex docs](https://katex.org/docs/autorender.html) to your `customHeadHTML` should do it.
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
    });
</script>
```
