### ISSUE TITLE
Light style code syntax highlight

### ISSUE THREAD

**Issue by dbrg77** [526avijitgupta/gokarna#102]
Hello, thanks for making this theme. I have been using it for a while and am quite happy with the feel.

I recently have a problem with syntax highlighting of code blocks when using any light theme.

For example, my current style defined in `config.toml` is `pygmentsStyle = "dracula"`, which yields the following look of a python code:

<img width="778" alt="Screenshot 2022-07-07 at 11 00 33" src="https://user-images.githubusercontent.com/7750032/177681433-9092e405-b4c7-493c-bfd7-3074c06864a6.png">

If I switch to `pygmentsStyle = "solarized-light"`, I got this output:

<img width="781" alt="Screenshot 2022-07-07 at 11 03 36" src="https://user-images.githubusercontent.com/7750032/177681764-f77b8297-0b89-469b-8667-1b4bed16df17.png">

How to remove the dark background of each line?

By the way, this is not specific to `solarized-light`. Basically, any light style will have this problem for me.

Regards,
Xi

**Comment by jamesericdavidson** [comment]
Adding another data point, as I can't reproduce this.

* Using the light theme and `solarized-light` as above.
* Using the Hugo version which appears in the openSUSE Tumbleweed OSS repo: `hugo version
hugo v0.101.0+extended linux/amd64 BuildDate=unknown`

No syntax highlighting:

![Screenshot 2022-07-28 at 10-28-29 Bandit Walkthrough](https://user-images.githubusercontent.com/109910326/181485811-8dba9bec-59b0-455e-9df0-91913b2a5de0.png)

bash:

![Screenshot 2022-07-28 at 10-28-10 Bandit Walkthrough](https://user-images.githubusercontent.com/109910326/181485835-5313a7aa-c689-4b6e-a7ce-c44286ee435e.png)

Hope this helps.

**Comment by dbrg77** [comment]
Ah, I see. This seems to be a Hugo version issue.

I was using `hugo v0.92.1-85E2E862 darwin/arm64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio`, which has the problem.

If now I used the latest, which is `hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 darwin/arm64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio`. The problem is solved. This is the new look with the latest version of Hugo:

<img width="554" alt="Screenshot 2022-07-29 at 17 22 56" src="https://user-images.githubusercontent.com/7750032/181728973-f5ff68a8-5c27-4414-99c2-fc3870c4987b.png">

Thank you @jamesericdavidson 

I think I will close this issue now!

**Comment by jamesericdavidson** [comment]
I'm glad it helped you :slightly_smiling_face:
