### ISSUE TITLE
Viability of licensing under the GPL vs AGPL

### ISSUE THREAD

**Issue by jamesericdavidson** [526avijitgupta/gokarna#112]
[The GNU Project outline the difference between the GPL and AGPL](https://www.gnu.org/licenses/why-affero-gpl.html) thusly:

> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

Currently, if somebody forks `gokarna` and runs the modified theme on their server, they are not compelled to release the code publicly. Ergo, the changes cannot be reviewed and potentially upstreamed.

If this is a concern for you, re-licensing may have some value. [The GNU Project and Free Software Foundation recommend the AGPL for server software](https://www.gnu.org/licenses/license-recommendations.en.html#server).

Regardless of the licence used, a [clarification on the version of the licence](https://www.gnu.org/licenses/identify-licenses-clearly.html) used would also be appreciated.

Hope this is helpful!

**Comment by 526avijitgupta** [comment]
@jamesericdavidson Thanks for bringing this up. We've used this license intentionally. We present Gokarna as an opinionated theme and we would want to give users who do not agree with us the flexibility to modify the code. 

Imo it should be up to them whether they want to keep the source public or private and whether they want to send changes upstream.
