### ISSUE TITLE
Table of Contents doesn't get rendered 

### ISSUE THREAD

**Issue by mansoorbarri** [526avijitgupta/gokarna#115]
These are my configuration as per GoKarna documentation but the table of contents isn't rendered.

config.toml: 
![](https://i.imgur.com/9AgM4R2.png)

start of the post:
 ![](https://i.imgur.com/5J8yXA8.png)

the page: https://mansoor.cf/posts/scambaiting101/

**Comment by yashmehrotra** [comment]
@mansoorbarri From the website link you posted, it seems like you are using an older version of the theme. Please update the git submodule of theme and try building again.

**Comment by mansoorbarri** [comment]
> @mansoorbarri From the website link you posted, it seems like you are using an older version of the theme. Please update the git submodule of theme and try building again.

issue fixed with update, thank you

**Comment by mansoorbarri** [comment]
the table of contents comes below the page but is fine when i view the site in incognito mode, is there in specific reason for it or it's just the browser's shenanigan

![2022_8](https://user-images.githubusercontent.com/90044118/184733714-26d8fa49-e627-443e-b7b9-602a880a1952.png)

**Comment by yashmehrotra** [comment]
@mansoorbarri This seems like a responsiveness issue, we are also working on adding table of contents for mobiles in #103 

Does the demo site render comments inline as well ?

**Comment by jamesericdavidson** [comment]
> is fine when i view the site in incognito mode

Have you tried testing this in a new, clean profile as well? Could be related to the Extensions, User Scripts, Content Blocking, et cetera, on your normal profile. Hence why it appears normal in Incognito mode.

**Comment by mansoorbarri** [comment]
it's fine everywhere except the current browser profile so it's probably that. thanks.
