### ISSUE TITLE
Add .Site.Copyright support

### ISSUE THREAD

**Issue by jamesericdavidson** [526avijitgupta/gokarna#118]
As mentioned in #111, [`.Site.Copyright` is a Hugo variable](https://gohugo.io/variables/site/#site-variables-list).

Will you accept a PR which adds this string to the footer? I have one ready to go.

**Comment by 526avijitgupta** [comment]
We already add copyright with a year. If someone wants to update this in the future, we'll encapsulate it into the `footerHTML`.

**Comment by jamesericdavidson** [comment]
> We already add copyright with a year

The `<footer>` uses `{{ now.Year }}`, which is not applicable to anything made in the past or future, hence the interest in adding it:

- If I have some content written before 2022, and not subsequently updated, the copyright date is not applicable
- Unless I update all content at 00:00 January 1 2023, the copyright date will not be applicable next year

I understand that you don't want to support this, just throwing my hat into the ring. Have a good one.
