### ISSUE TITLE
avatar

### ISSUE THREAD

**Issue by JoSuru** [526avijitgupta/gokarna#122]
Hi in which folder should I put the avatar I can't display it

**Comment by jamesericdavidson** [comment]
See [the documentation](https://gokarna-hugo.netlify.app/posts/theme-documentation-basics/#avatar-url).

Make a subdirectory of `static` called `images`, then a file called `avatar.jpg` into `static/images`. Hence, `/images/avatar.jpg`.

Note that the `static` directory is missing from the path.

Of course, it suffices to place any image file into the `static` directory, but I'm quoting the documentation verbatim to avoid confusion.

**Comment by yashmehrotra** [comment]
Thanks for the help @jamesericdavidson 

Hope this helps you @JoSuru
