### ISSUE TITLE
View is skewed on mobile

### ISSUE THREAD

**Issue by jamesericdavidson** [526avijitgupta/gokarna#125]
See the below screenshots for reference.

This appears using browser emulation (Firefox) and on an actual device (Chromium on Pixel 4a (not 5G)).

### Browser Emulation

![skewed](https://user-images.githubusercontent.com/109910326/191049971-484aea13-cf2a-4cef-b055-eb5147072f5d.png)

### Actual Device

![skewed-mobile](https://user-images.githubusercontent.com/109910326/191050965-630a6df2-28c2-4132-9d02-3e530d4b7a16.png)

**Comment by dchiquito** [comment]
This looks like it's there intentionally, for what reason I could not say:
![image](https://user-images.githubusercontent.com/577946/201974341-b043bfd7-282f-4792-9272-944d5e5c0c94.png)

**Comment by jamesericdavidson** [comment]
Thanks @dchiquito! CSS scares me :ghost:
