### ISSUE TITLE
Wide date strings are always wrapped on posts page

### ISSUE THREAD

**Issue by dchiquito** [526avijitgupta/gokarna#128]
Even on the largest breakpoint, wide date strings like `September 22, 2022` are always wrapped around to a new line:
![image](https://user-images.githubusercontent.com/577946/194195051-0f967583-b9d1-41cb-8b8c-e65a34c2b81d.png)
Scaling the window smaller will eventually cause other dates to wrap, but `September 22` specifically will never display normally.

**Comment by yashmehrotra** [comment]
@dchiquito Yeah, this issue is probably because of the way we format date. Do you think using the `Sep 22, 2022`/`Oct 2, 2022` format will help ? I find it more pleasing to look at as well

@526avijitgupta What are your thoughts

**Comment by dchiquito** [comment]
I can't test right now, but IIRC the title div is set to `width: 80%`, which leaves 20% for the date. Adjusting that ratio a bit worked when I tested it, but it moves all the dates around.

I think the best way would be to `flex-grow: 1` the title column, but shortening the date string would work as well

**Comment by dchiquito** [comment]
I can't test right now, but IIRC the title div is set to `width: 80%`, which leaves 20% for the date. Adjusting that ratio a bit worked when I tested it, but it moves all the dates around.

I think the best way would be to `flex-grow: 1` the title column, but shortening the date string would work as well

**Comment by 526avijitgupta** [comment]
@yashmehrotra Using the other date format sounds good to me

**Comment by 526avijitgupta** [comment]
@dchiquito I'm fine with either solution. Using flex properties sounds ideal. In case you test it out and want to raise a PR, feel free to do so :)

**Comment by dchiquito** [comment]
I tried using `flex-grow`, but that caused all the dates to be right-aligned, which looked ugly. Instead I just experimented with lowering the post title width until it didn't wrap anymore. Very short dates would have a significant amount of padding on the right, but that's the cost of left-aligning.
