### ISSUE TITLE
Support for other languages with config.toml

### ISSUE THREAD

**Issue by ghost** [526avijitgupta/gokarna#132]
I am trying to make it showcase Chinese, so I add content blowing:
~~~toml
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
~~~
But it doesn't work.

I am using hugo `hugo v0.104.2-84cbe724983b4b6153fd39aae0888cbb89a56cda windows/amd64 BuildDate=2022-09-29T10:31:09Z VendorInfo=gohugoio`

**Comment by mansoorbarri** [comment]
you have to use `[languages]` param in `config.toml`. More information: https://gohugobrasil.netlify.app/content-management/multilingual/

**Comment by 526avijitgupta** [comment]
Yeah I'm gonna close this. Thanks @mansoorbarri
