### ISSUE TITLE
Posts sometimes break when they should not

### ISSUE THREAD

**Issue by lzap** [526avijitgupta/gokarna#140]
Hey,

I am not sure what is going on but some posts do break on my page regardless they are short in width:

<img width="843" alt="Snímek obrazovky 2022-11-13 v 20 00 14" src="https://user-images.githubusercontent.com/49752/201539378-66ce75a5-0bff-4fd2-880a-fae75365ac73.png">

Anything I can do about this? I see a div element with flex-break class, what this is for? Thanks for help.

**Comment by lzap** [comment]
This fixed it, not sure what I did tho:

```css
  .post-title .post-link {
    width: 70%;
  } 
```

**Comment by jamesericdavidson** [comment]
What resolution is this? I assume it's high enough for the CSS to recognise it as a desktop or laptop, and I'm guessing that the November strings are too long and have to break.
