### ISSUE TITLE
Remove "s" from titles 

### ISSUE THREAD

**Issue by mansoorbarri** [526avijitgupta/gokarna#147]
Hey, is there any way to remove "s" from the title text like the one here: 

![image](https://user-images.githubusercontent.com/90044118/209456840-422bd0fc-4f00-42f8-a5af-68af5c8c074c.png)

**Comment by yashmehrotra** [comment]
You need to put: 
```
pluralizelisttitles: false
```

in your config

Source: https://discourse.gohugo.io/t/how-can-i-stop-section-title-from-showing-up-as-plural/994/5

**Comment by mansoorbarri** [comment]
still the same 

![image](https://user-images.githubusercontent.com/90044118/209457563-2e01985f-d71c-4a96-b3eb-4c7e06ae0064.png)

**Comment by yashmehrotra** [comment]
@mansoorbarri This should be false, not true

**Comment by mansoorbarri** [comment]
no change

![image](https://user-images.githubusercontent.com/90044118/209458051-4aefb5a5-d74c-415e-abf0-83f8a3ad6162.png)

**Comment by mansoorbarri** [comment]
i added ``` pluralizelisttitles = false``` outside params and it worked, thank you
