### ISSUE TITLE
Github icon and light-dark mode button is shifted on mobile 

### ISSUE THREAD

**Issue by mansoorbarri** [526avijitgupta/gokarna#148]
I have this issue where on my mobile some icons are shifted towards the left, it is fine on my PC doe. The config file seems fine too so i don't really know that is wrong.

my site/demo: mansoorbarri.com

![image](https://user-images.githubusercontent.com/90044118/209690581-3d32725a-151e-4c90-8c1b-37662db5ee13.png)

**Comment by jamesericdavidson** [comment]
Can't reproduce. What browser and device are you using?

-------- Original Message --------

**Comment by mansoorbarri** [comment]
Chrome on Samsung A02. Only this phone is showing this bug and browser on my laptop using "Inspect" to check the responsiveness
