### ISSUE TITLE
How to add images in posts?

### ISSUE THREAD

**Issue by atulraj85** [526avijitgupta/gokarna#153]
Have tried putting the images at the directory "static" and in the same directory as .md file.

**Comment by yashmehrotra** [comment]
Can you share a screenshot of the network tab when they load ? Some hosting providers do not serve `static/`

Also, try following the same structure in `exampleSite`

**Comment by atulraj85** [comment]
Thank you! I tried what you said, looked into the examplesite and I had misconfigured the config.toml file. So it's working now.
