### ISSUE TITLE
Adding caption to images in Markdown

### ISSUE THREAD

**Issue by fabrizio-ottati** [526avijitgupta/gokarna#158]
Is there a way to add a caption to the images in the blog posts?

**Comment by jamesericdavidson** [comment]
Not in Markdown, but you can use the Hugo shortcode:

https://gohugo.io/content-management/shortcodes/#figure

Regards,
Jimmy

-------- Original Message --------

**Comment by fabrizio-ottati** [comment]
Thanks! Is there any way to center the caption?

**Comment by jamesericdavidson** [comment]
You can add this to `main.css`:

```
figcaption {
text-align: center;
}
```

Or you can make your own shortcode:

https://gohugo.io/templates/shortcode-templates/#single-named-example-image

Regards,
Jimmy

-------- Original Message --------

**Comment by jamesericdavidson** [comment]
Emails don't support Markdown, so in this file:

```
static/css/main.css
```

Add this:

```
figcaption {
    text-align: center;
}
```

**Comment by fabrizio-ottati** [comment]
fantastic! Thank you very much :)

**Comment by jamesericdavidson** [comment]
Happy to help
