### ISSUE TITLE
og:image doesn't work properly 

### ISSUE THREAD

**Issue by mansoorbarri** [526avijitgupta/gokarna#159]
So basically i have image set for every post but it doesn't show it either when sharing the link or when testing via a tool like https://socialsharepreview.com/

For example - 
Post: https://mansoorbarri.com/articles/admin-vs-standard/
Front matter: 
```
---
title: "Admin User vs Standard User"
date: 2023-03-01
tags: [Info]
image: "/images/articles/admin-vs-standard/main.webp"
type: "post"
showtableOfContents: true
---
```
test: 
![image](https://user-images.githubusercontent.com/90044118/229316615-63d78ec7-847b-4398-8a4a-03b71a9886a9.png)

ik that the image and the url is correct as it is embedded on the post

**Comment by yashmehrotra** [comment]
Thanks for reporting. This is fixed by #160 , the problem was that we were not using absolute urls

Pull the latest main branch for the changes, the demo [gokarna site](https://gokarna-hugo.netlify.app) is also working on https://socialsharepreview.com
