### ISSUE TITLE
Features: Add option to show more informations (such as projects) on homepage instead of only posts

### ISSUE THREAD

**Issue by Resist4263** [526avijitgupta/gokarna#161]
Hello, I hope that this theme can add option to show more information, such projects, talks on homepage, instead of only posts. The current homepage is a little empty and don't show visitors more key infromation.

**Comment by yashmehrotra** [comment]
@Resist4263 You can add any content to the homepage in markdown by adding a `content/_index.md` file

**Comment by Resist4263** [comment]
@yashmehrotra But the content in _index.md will display in center.

**Comment by yashmehrotra** [comment]
How would you want it to be displayed then?

**Comment by yashmehrotra** [comment]
You can write HTML in markdown.
`_index.md` should look like

```
---
---
<div style="width:0px;">Left Justified</div>
```
Note: The empty `---` frontmatter is important

Also, add this in config.toml
```
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
``` 

Ref:
- https://github.com/gohugoio/hugo/issues/7296
- https://stackoverflow.com/questions/61292854/with-hugo-can-we-use-html-code-in-a-md-file

**Comment by Resist4263** [comment]
Thanks a lot, that works for me!
