### ISSUE TITLE
Can I contribute comment function for this theme? I would like to use cusdis.com 

### ISSUE THREAD

**Issue by akakshuki** [526avijitgupta/gokarna#162]
Hi developer team, 
I would like to apply the free comment service to your theme. My free service is [cusdis.com](cusdis.com) and set the required condition in `toml` file

**Comment by akakshuki** [comment]
my document following here [discourse.gohugo.io](https://discourse.gohugo.io/t/free-and-open-source-comments-for-hugo/32940/18)

**Comment by yashmehrotra** [comment]
@akakshuki Thank you for reaching out. 

We do not add vendor specific logic in our code. To achieve this, users can just use `params.customFooterHTML`  in their config and add any commenting platform.

**Comment by akakshuki** [comment]
ah Great, I saw you have updated your template. Thanks for the useful feature
