### ISSUE TITLE
`avatarAltText` config parameter isn't documented

### ISSUE THREAD

**Issue by BWPanda** [526avijitgupta/gokarna#166]
`avatarAltText` is a config parameter used in: https://github.com/526avijitgupta/gokarna/blob/main/layouts/index.html#L5

While it *is* mentioned in the [example config](https://github.com/526avijitgupta/gokarna/blob/main/exampleSite/config.toml#L16), it's _not_ mentioned in the documentation:
- https://github.com/526avijitgupta/gokarna/blob/main/exampleSite/content/posts/theme-documentation-basics.md
- https://github.com/526avijitgupta/gokarna/blob/main/exampleSite/content/posts/theme-documentation-advanced.md

**Comment by BWPanda** [comment]
Looks like this was added recently in: https://github.com/526avijitgupta/gokarna/pull/120

**Comment by mansoorbarri** [comment]
close this pr?
