### ISSUE TITLE
Show lastmod date on post

### ISSUE THREAD

**Issue by luanalatte** [526avijitgupta/gokarna#168]
Hi, I have a suggestion: can we make it so that posts show their last modified time in addition to (or in place of) the regular date?

This is how I implemented it as a temporary solution in my site: [gitlab commit](https://gitlab.com/luanalatte/luanalatte.gitlab.io/-/commit/f81746a8312de297751e97be1e1dfa1ddf600472)

**Comment by yashmehrotra** [comment]
@luanalatte Sure, can you create a PR for this ?

**Comment by luanalatte** [comment]
There it is! https://github.com/526avijitgupta/gokarna/pull/169
