### ISSUE TITLE
Social icons do not render

### ISSUE THREAD

**Issue by holmesrichards** [526avijitgupta/gokarna#180]
Not sure if this is the same issue as https://github.com/526avijitgupta/gokarna/issues/88 or not, and either way I'm not sure how to proceed. My site is at https://richholmes.xyz, hosted at Dreamhost. The SVG icons in the header are rendered, but the social icons are not. When I do "hugo serve" locally they do render.

**Comment by holmesrichards** [comment]
Error in the console is:

www.richholmes.xyz/:1 Access to XMLHttpRequest at 'https://richholmes.xyz/svg/icons/mastodon.svg' from origin 'https://www.richholmes.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by yashmehrotra** [comment]
@holmesrichards CORS are something which is controlled entirely by the Host Server. You should probably look into tweaking the server settings to solve this

**Comment by 526avijitgupta** [comment]
Should be fixed now that https://github.com/526avijitgupta/gokarna/pull/178 is merged
Please check @holmesrichards

**Comment by holmesrichards** [comment]
Looks good, thanks!
