### ISSUE TITLE
h1 header text on posts page

### ISSUE THREAD

**Issue by holmesrichards** [526avijitgupta/gokarna#189]
Is it possible to change the h1 header text on the Posts page? I mean, I find if I change the name of the posts directory that changes the text — though in variable ways, sometimes it just uses the directory name, sometimes it adds an "s", sometimes it adds "es". But if I wanted it to say for instance "John Smith's Fabulous Blog Posts" how would I do that? Short of changing the directory name to "John Smith's Fabulous Blog Posts".

**Comment by holmesrichards** [comment]
Answering my own question in case it helps others, and asking a followup:

To change the h1 header text, create posts/_index.md with type: post and title: "John Smith's Fabulous Blog Posts".

Content of this file below the header appears to be ignored.

Followup: Is there a way to add text that will appear above the listing of posts?

**Comment by yashmehrotra** [comment]
> Answering my own question in case it helps others, and asking a followup:
> 
> To change the h1 header text, create posts/_index.md with type: post and title: "John Smith's Fabulous Blog Posts".
> 
> Content of this file below the header appears to be ignored.

Thanks for this

> Followup: Is there a way to add text that will appear above the listing of posts?
Do you want to add a text above H1 ? can you send a rough picture/mockup of what you intend ?

**Comment by holmesrichards** [comment]
Something like this:

![Untitled](https://github.com/526avijitgupta/gokarna/assets/56895621/b36ef0d2-9929-4d3d-8a70-05adfabd6364)

**Comment by holmesrichards** [comment]
This does *almost* what I want: Copy `themes/gokarna/layouts/partials/list.html` to `layouts/partials` and add

```
  {{ .Content }}
```

where I want it (after the H1 header). Then add content to the `posts/_index.md` file:

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/41e524b7-14a1-4062-8c19-9df065538f7f)

Result looks like

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/a13088cf-0da5-496f-8a04-68d12f4875ae)

The one problem is the HTML link. It's there and it is functional, but it is not underlined as links are on other pages.

On the other hand if instead of a custom `layouts/partials/list.html` I create `layouts/_default/list.html` containing

```
{{ define "main" }}
    {{ if eq .Type "page" }}
        {{- partial "page.html" . -}}
    {{ else }}
        {{ .Content }}
        {{- partial "list.html" . -}}
    {{ end }}
{{ end }}
```
the result looks like

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/37a0325c-c1eb-47ae-b2e0-d302309f44ad)

Now the link is underlined. But the content appears above the H1 header, which is not what I'd prefer, and it's wider than the rest of the page.

**Comment by holmesrichards** [comment]
This does *almost* what I want:

Copy `themes/gokarna/layouts/partials/list.html` to `layouts/partials/list.html` and add

```
  {{ .Content }}
```
after the H1 header. Then add content to `content/posts/_index.md`:

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/1a02f80f-ee68-4e37-8e60-302dd7ebd9c2)

Result looks like

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/f3359fbb-69e4-49b4-9a9d-832be90e1b43)

The one problem is the HTML link. It is there and it is functional but it is not styled with underline as with links elsewhere on the site.

On the other hand, if instead of a custom `partials/list.html` I create `layouts/_default/list.html` containing

```
{{ define "main" }}
    {{ if eq .Type "page" }}
        {{- partial "page.html" . -}}
    {{ else }}
        {{ .Content }}
        {{- partial "list.html" . -}}
    {{ end }}
{{ end }}
```
then it looks like

![image](https://github.com/526avijitgupta/gokarna/assets/56895621/3f01fe23-59e9-4e84-85a7-abc0da44b716)

Now the link is underlined, but the content is above the H1 header, which is not what I would prefer, and its width is larger than the rest of the page.

**Comment by holmesrichards** [comment]
The above custom `partials/list.html` with suitable css tweaking does what I want, I think.
