### ISSUE TITLE
External AvatarURL

### ISSUE THREAD

**Issue by luanalatte** [526avijitgupta/gokarna#193]
How should I go about using an external URL for my avatar? since both `header.html` and `index.html` refer to it as
`{{ .Site.BaseURL }}{{ .Site.Params.AvatarURL }}`
I would need to get rid of the baseURL part, but overriding those two files entirely just for this change seems silly.

Is there an alternate solution here that I'm missing? If not, I thought about splitting the `img` tag into an `avatar.html` partial that can be easily overriden on its own (although it requires a couple extra tweaks to re-implement the `size-*` classes.

**Comment by yashmehrotra** [comment]
Nice find, I'll update the template to handle external urls
