### ISSUE TITLE
Footer wraps on mobile screen

### ISSUE THREAD

**Issue by 526avijitgupta** [526avijitgupta/gokarna#205]
Looks like the recent fix to limit the footer width to `40%` to prevent overlap with a ToC item has led to the footer text now wrapping easily, even when there seems to be enough space for the text to fit in one line.

See screenshot of how it looks on my mobile.

![Screenshot_20231121-005535.png](https://github.com/526avijitgupta/gokarna/assets/7583815/51d38c1c-af24-47de-a0fe-e9da025d82e4)

cc @mansoorbarri

**Comment by yashmehrotra** [comment]
@526avijitgupta I think we should set a footer length limit and if that is crossed which should not care for wrapping

In 99% of the cases, the footer is not a very long string

**Comment by mansoorbarri** [comment]
should we even wrap the footer then? @yashmehrotra
