### ISSUE TITLE
Plausible analytics

### ISSUE THREAD

**Issue by mwolff44** [526avijitgupta/gokarna#214]
Hi,
First, thanks for this great theme. I want to use plausible as analytic platform, but i do not see how to integrate the theme with https://github.com/divinerites/plausible-hugo.
I can modify directly the head partial, but not sure that the idea is ok.
Thanks

**Comment by mansoorbarri** [comment]
you probably have to edit the header yourself because using plausible is quite subjective

**Comment by mwolff44** [comment]
OK, i will do that. Thanks for your answer.
