### ISSUE TITLE
FR: Per-post copyright dates; site-wide copyright licence header

### ISSUE THREAD

**Issue by jamesericdavidson** [526avijitgupta/gokarna#222]
Hello chaps,

I maintained a fork of Gokarna for a while with the above features. Would you be interested in reviewing a PR with either of these? I saw that `lastmod` eventually got through, so wondered if your position on these features had changed as well.

In short:-

## Per-post dates

Calculates the date range between `date` and `lastmod`, e.g.

```
date: 2021-01-01
lastmod: 2023-09-05

(C) John Smith 2021-2023
```

This is in contrast to displaying the copyright date as the current year.

## Site-wide copyright licence header

Declarable text in `config.toml` which appears in the footer of every post or page, but not other site pages (such as home, tags).

Many thanks in advance :ok_hand:

**Comment by yashmehrotra** [comment]
@jamesericdavidson 

Sure, we would love to have those features are feature flaggable under `config.copyright.<>` and add the usage in the advanced docs

Thanks for your contribution

**Comment by jamesericdavidson** [comment]
Thanks. The draft PR is up #233, so closing this.
