### ISSUE TITLE
`socialIcons` disappear when ad blockers are enabled.

### ISSUE THREAD

**Issue by ryouze** [526avijitgupta/gokarna#238]
I noticed that the `socialIcons` (GitHub, E-mail, Twitter, etc.) disappear after my site is deployed via GitHub Actions. At first, I thought it might be a caching issue, but after testing on multiple browsers and devices, the icons still wouldn’t appear. The GET requests for the images are being made, but they just don’t render (except in Safari).

After digging deeper, I found out that ad blockers are causing this issue. It seems like `SVGInjector` is triggering them, but this requires further investigation. What’s odd is that the icons show up perfectly when running the site locally with `hugo server`.

Is this something that could realistically be fixed without breaking the current API? I understand that most users don’t use ad blockers, so this might be outside the scope of the project, but I thought I’d ask anyway.

```html
<a href="https://example.com" aria-label="Learn more on twitter">
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="injected-svg svg-inject"><title>Twitter</title><path d="..."></path></svg>
</a>
```

```js
// assets/js/main.js

const svgsToInject = document.querySelectorAll('img.svg-inject');
SVGInjector(svgsToInject);
```

### Broken: Firefox with uBlock Origin (macOS)
![firefox-adblock](https://github.com/user-attachments/assets/21b79c78-0607-4359-b6e1-804be9ce895e)

### Broken: Chrome with uBlock Origin Lite (macOS)
![chrome-adblock](https://github.com/user-attachments/assets/01d152a5-8fca-4c5e-bad4-d397d8f9a919)

### Broken: Safari with AdGuard Pro (iOS)
![ios-adblock](https://github.com/user-attachments/assets/35bff7b5-e629-4a32-b8f4-21aebba48122)

Also the footer breaks in landscape view when ad block is enabled.

![ios-adblock-landscape](https://github.com/user-attachments/assets/b393664f-4ebb-48bb-ad53-9242f861c5ec)

### Working: Safari with Wipr (macOS)
![safari-adblock](https://github.com/user-attachments/assets/6c747e18-66c9-4a22-89a1-29124a37a5b7)

**Comment by ryouze** [comment]
I completely forgot about the logger in uBlock Origin 🫢

The issue is caused by the `##.social-icons-list` filter. If you disable the `EasyList – Social Widgets` filter, the icons show up as expected. Perhaps the `.social-icons-list` class could be renamed.

![logger](https://github.com/user-attachments/assets/af3a17ec-c43e-4ca9-836a-fd625620237f)

**Comment by jamesericdavidson** [comment]
Using uBlock Origin as an example, this breakage is *entirely* dependent on the filters and rules you are using. [The default Easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode) has zero issues. @ryouze You already identified this as I was making this comment.

Trying to solve for millions of different browser configurations in this repo is folly.

**Comment by ryouze** [comment]
I fixed the issue on my end by renaming `social-icons-list` to `gk-social-icons-list` (with `gk` standing for Gokarna).

Would you like me to submit a PR? I understand the issue comes from an overly aggressive adblock filter, which isn’t enabled by default.

**Comment by jamesericdavidson** [comment]
> Would you like me to submit a PR? I understand the issue comes from an overly aggressive adblock filter, which isn’t enabled by default.
 
@ryouze I think you should do this, just highlighting that it may happen again :wink:
