### ISSUE TITLE
SVG Injection bug when hosting on non-canonical url

### ISSUE THREAD

**Issue by alanmcruickshank** [526avijitgupta/gokarna#255]
Hello. First: great theme 👍 . Thanks for putting this together.

We've just started using this theme on the homepage for the open source project SQLFluff: https://sqlfluff.com

In local development (using `hugo server`), the feather icons render fine, and when deployed (i.e. actually at `sqlfluff.com`, built using `hugo --gc --minify`) the feather icons _also_ render fine. However, we use netlify for development builds, which naturally deploy to a different url (for example right now you can find a deployment preview demonstrating this issue here: https://deploy-preview-8--sqlfluff.netlify.app/).

In that environment, the feather icons don't resolve. I've had a look at the console, and I can see the following errors:
![image](https://github.com/user-attachments/assets/5abc9508-922d-4451-a373-484785e400b9)

It looks like the javascript to inject the svg files is trying to resolve the paths on the production domain, but they a) don't exist there yet in this case and b) even the ones that do raise a CORS error.

What's puzzling me is that it works fine in development, where the url is `localhost`, even when the svg images aren't deployed in production. That's as far as I've got in my debugging, but I'd love a way to force the svg injection to use a relative path so that it doesn't care what domain it's deployed on. Is that possible?

I'm happy to raise a PR if you give me some pointers on where the path resolution happens, but my javascript fu was not good enough to work that out on my own.

**Comment by jamesericdavidson** [comment]
Hi Alan,

Have you looked into the CORS errors? At first blush this looks like it's caused by the disparity between domains.

Regards,

James Davidson

-------- Original Message --------

**Comment by alanmcruickshank** [comment]
Thanks @jamesericdavidson . I agree, and I've done some digging and found the issue. I think my issue is caused by the #249, and the fix used there. By moving to `absUrl`, we resolve the issue of non-root hosting, but in turn break references when hosting on a different domain.

**Comment by alanmcruickshank** [comment]
Would you be open to switching from `absUrl` to `relUrl` there? I think that should solve both issues.

Docs links:
- `relUrl`: https://gohugo.io/functions/urls/relurl/
- `absUrl`: https://gohugo.io/functions/urls/absurl/

cc @pkierski as the author of #249

**Comment by alanmcruickshank** [comment]
@jamesericdavidson - for reference, if you look at the deploy preview for this repository on #249 - the social icons are broken. That's probably a fair demonstration that it's not just on the sqlfluff project that this issue is happening. I've confirmed on my project that switching to `relUrl` solves the issue.

**Comment by pkierski** [comment]
> Would you be open to switching from `absUrl` to `relUrl` there? I think that should solve both issues.

Definitely. I've just tested `relUrl` as solution for non-root hosting and it works well.
