### ISSUE TITLE
can't view post in home page

### ISSUE THREAD

**Issue by alexdelli** [526avijitgupta/gokarna#77]
Hi, please could you help me?
I switch from a previous theme to gokarna, but I can0t view the index page with all blog post.
What I'm doing wrong?
thank you

https://github.com/alexdelli/alexpress

**Comment by sriveravi** [comment]
Were you ever able to fix? I am running into the same problem. 

I start with the template, set my theme as "gokarna". Overall, I get the look of the theme when I serve it locally. However, when I click on "posts", I get a "404 not found" error.

**Comment by alexdelli** [comment]
no, I change theme 😭

**Comment by sriveravi** [comment]
It must be a bug and probably a very simple and silly one. I may take a stab in the theme files to see if I spot anything. Im not a hugo expert but I can try.

**Comment by sriveravi** [comment]
Okay, I spent some time tinkering and testing things out. Here is what I found that was able to get the blog page to show:

In the header, make sure you set:

~~~
draft: false
~~~

or entirely remove the draft line.

**Comment by 526avijitgupta** [comment]
@yashmehrotra Could you please have a look? Seems like an issue with templating

**Comment by yashmehrotra** [comment]
It looks like the problem was that the posts' draft option was set to true. Closing this for now, please re-open if not fixed.
