### ISSUE TITLE
Theme cannot be used when building to a subdirectory

### ISSUE THREAD

**Issue by jmooring** [526avijitgupta/gokarna#79]
This produces a site with 404's for CSS, JS, etc.

```
baseURL = 'https://example.org/foo/'
```

You've hardcoded links to the root of the domain rather than the root of the site.

**Comment by 526avijitgupta** [comment]
Hi @jmooring thanks for reporting this! Do you have a reproducible example of the same?

**Comment by jmooring** [comment]
Are you unable to reproduce this problem yourself? It is... your theme.

**Comment by GiovanniK** [comment]
Same problem here. 
It's because the theme uses absolute paths: /css/style.css, /js/script.js etc.

**Comment by ericklerma** [comment]
Same problem here, maybe if they fix the bug, I might consider making a donation

**Comment by 526avijitgupta** [comment]
@ericklerma @GiovanniK @jmooring We've pushed a fix. Should be working now
