### ISSUE TITLE
Homepage social icons too big

### ISSUE THREAD

**Issue by netotz** [526avijitgupta/gokarna#82]
Using the `socialIcons` setting of `params` renders big icons:

![image](https://user-images.githubusercontent.com/5118942/156820768-802798a1-c11d-4f0a-bfb7-ee732c1b4f26.png)

This is the site that I'm rendering: https://github.com/netotz/netotz.github.io

Right now the source code doesn't include the social icons because of it looks.

**Comment by 526avijitgupta** [comment]
@netotz I just tried to reproduce it locally by cloning in a fresh copy of the theme. The css which sets height and width of an icon is present [here](https://github.com/526avijitgupta/gokarna/blob/main/static/css/main.css#L346-L348) and it seems to be getting applied as expected.

1. Please double check that you've configured the social icons exactly as described in the "Icons " section of [documentation](https://gokarna-hugo.netlify.app/posts/theme-documentation-advanced/) :) 
2. If it still doesn't work, please share your config.toml file (specifically the part where you're configuring `socialIcons` config param) and I'll be happy to help!

**Comment by netotz** [comment]
I doubled check the documentation and this is the relevant section of `config.toml`, still doesn't work:
```toml
[params]
    socialIcons = [
        {name = "github", url = "https://github.com/netotz"},
        {name = "linkedin", url = "https://www.linkedin.com/in/netotz/"},
    ]
```

I noticed something odd. This site is being published to GitHub Pages with GitHub Actions. The [published site](https://netotz.github.io/) has the latest dark theme color, but not my local render when I run `hugo serve` as you can see in the posted image above, so it's not using the latest version of Gokarna although I already updated the submodule. I think the issue is related to this, but I don't know why Hugo is not using the latest version of the theme. Have you seen this or similar before with Hugo?

**Comment by 526avijitgupta** [comment]
@netotz That is odd. I would suggest:

1. Try opening the site in private or incognito mode in your browser.

2. Run `hugo mod clean` which deletes module cache for the current project and build the project again

3. If the above steps do not work then clone a fresh copy of your repository to see if that works. 

3. Lastly you could maybe check network tab of your browser to see if static resources (specifically `main.css` in this case) are being correctly loaded or not.

**Comment by netotz** [comment]
@526avijitgupta running `hugo mod clean` worked. Thanks! Issue solved :)

By the way, if I want to keep using the previous dark background, which files should I edit? I don't want to edit the files of the Gokarna theme because it's a git submodule, so I wonder if there's a parameter to set a custom background color in dark mode.
