### ISSUE TITLE
Custom background color in dark mode

### ISSUE THREAD

**Issue by netotz** [526avijitgupta/gokarna#83]
@526avijitgupta running `hugo mod clean` worked. Thanks! Issue solved :)

By the way, if I want to keep using the previous dark background, which files should I edit? I don't want to edit the files of the Gokarna theme because it's a git submodule, so I wonder if there's a parameter to set a custom background color in dark mode.

_Originally posted by @netotz in https://github.com/526avijitgupta/gokarna/issues/82#issuecomment-1060940301_

**Comment by yashmehrotra** [comment]
@netotz We keep all the colors as variables in the `/static/css/dark.css` file. Changing [these lines](https://github.com/526avijitgupta/gokarna/blob/main/static%2Fcss%2Fdark.css#L1-L6) would change the dark background color.

We currently do not expose those as parameters, but can look into it if more people also have the same usecase

**Comment by 526avijitgupta** [comment]
Closing for now. If there's more interest this can be reopened in the future

**Comment by klercke** [comment]
Apologies for the necro, but I am also interested in this feature
