### ISSUE TITLE
Avatar Issue

### ISSUE THREAD

**Issue by DaBlazePRO** [526avijitgupta/gokarna#84]
On pages except the homepage the avatar doesn't show up pls help
![image](https://user-images.githubusercontent.com/88505509/159789292-9878ef67-ebe9-4db8-985d-6495e917e85b.png)

**Comment by 526avijitgupta** [comment]
@DaBlazePRO Thanks for reporting this. I couldn't reproduce the issue. Please try one of the following if you still need help:

1. Try opening the site in private or incognito mode in your browser.

2. Run `hugo mod clean` which deletes module cache for the current project and build the project again

3. If the above steps do not work then clone a fresh copy of your repository to see if that works.

**Comment by DaBlazePRO** [comment]
I have done all of this but it still doesn't work here is my toml. I also have an issue where social icons wont show up in the html version of the site.

`baseURL = '/'
languageCode = 'en-us'
title = 'Avalanche'
theme = 'gokarna'
enableRobotsTXT = true

[params]
  footer = "Avalanche"
  description = "Fun Gaming Community and Minecraft Server!"
  avatarURL = "logo.png"
  avatarSize = "size-l"
  customHeadHTML = """
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  socialIcons = [
    {name = "twitter", url = "https://example.com"},
    {name = "instagram", url = "https://example.com"},
    {name = "twitch", url = "https://www.twitch.tv/dablazelive"},
    {name = "discord", url = "https://discord.gg/vqsWH7Hb9r"}
  ]`

**Comment by yashmehrotra** [comment]
@DaBlazePRO It looks like javascript and assets are not being loaded properly, when you open the website, do you see any irregularities in the network tab ?

**Comment by DaBlazePRO** [comment]
Yes, the link to the website is https://cloudy-fi.com/

can you please go to a page other than the homepage and see what is happening?

**Comment by yashmehrotra** [comment]
@DaBlazePRO The logo is not being loaded because the path is incorrect. Use `/logo.png` instead of `logo.png`

Also, for social icons, there seems to be an issue with your hosting provider since the icon paths are being 404'd

**Comment by DaBlazePRO** [comment]
Is there anything I can do to fix the social icons?
