### ISSUE TITLE
Support TabelOfContent

### ISSUE THREAD

**Issue by NYH-Dolphin** [526avijitgupta/gokarna#85]
I really like your hugo website design. It's simple and beautiful. Well, this is just an advice. I am wondering whether it can add the TOC supporting so that there is a catalogue displayed in the side when we read the blog?

**Comment by yashmehrotra** [comment]
@NYH-Dolphin Thank you for raising this feature request. Even we were planning to add a Table of Contents. We'll come up with a design for this and hopefully it will be a part of the next release 😄

**Comment by NYH-Dolphin** [comment]
> @NYH-Dolphin Thank you for raising this feature request. Even we were planning to add a Table of Contents. We'll come up with a design for this and hopefully it will be a part of the next release 😄

Thank you so much for Updating Table Of Content in time!! I can't wait to use the new features 😊

**Comment by NYH-Dolphin** [comment]
> @NYH-Dolphin Thank you for raising this feature request. Even we were planning to add a Table of Contents. We'll come up with a design for this and hopefully it will be a part of the next release 😄

Thank you so much for Updating Table Of Content in time!! I can't wait to use the new features 😊

**Comment by yashmehrotra** [comment]
@NYH-Dolphin We have merged the Table of Contents change, here is the documentation link to configure: https://gokarna-hugo.netlify.app/posts/theme-documentation-advanced/#table-of-contents
