### ISSUE TITLE
How to add pictures to homepage

### ISSUE THREAD

**Issue by DaBlazePRO** [526avijitgupta/gokarna#86]
Im not sure if a theme decides this or if hugo is capable of doing this but, am i able to add an image to the homepage?

**Comment by yashmehrotra** [comment]
@DaBlazePRO It is possible to add your avatar on the homepage using `avatarURL`. You can use this documentation: https://gokarna-hugo.netlify.app/posts/theme-documentation-basics/#avatar-url

**Comment by DaBlazePRO** [comment]
I know about that but can you add pictures onto the homepage like you can in a post?

**Comment by yashmehrotra** [comment]
@DaBlazePRO No, we currently don't support that functionality
