### ISSUE TITLE
hierarchy of pages

### ISSUE THREAD

**Issue by ToddBradley** [526avijitgupta/gokarna#96]
What is the best way to make a site using `gokarna` that uses a hierarchy of pages? For example, suppose the example site had `projects/javascript` and `projects/php` instead of simply `projects`.

**Comment by yashmehrotra** [comment]
@ToddBradley You can just create subfolders inside the projects directory and add an `_index.md` file as the homepage for that. Example:

```
projects
├── _index.md
├── javascript
│  └── _index.md
├── php
   └── _index.md
```

And the URL for these will be `/projects/javascript` and `/projects/php` respectively

**Comment by yashmehrotra** [comment]
@ToddBradley I'm afraid we don't automatically build navigation menus to include any subfolders (or to be specific, we don't do any automation for navigation menus at all)

Can you please send us the theme you are coming from ?

**Comment by ToddBradley** [comment]
> Can you please send us the theme you are coming from ?

Sorry, I just realized I didn't answer your question. One of my sites uses Ananke, which does what they call "pagination" to automatically build a way to navigate to those sub-pages. Another site uses theme Eureka, which does the same but looks different.
