### ISSUE TITLE
Fix indexing bug of TableOfContent

### ISSUE THREAD

**Issue by NYH-Dolphin** [526avijitgupta/gokarna#97]
Hi! I have started to use the TOC now. But I found that there was a problem:
If you use H1-6 in markdown start **with a number**
 eg.
### 1. This is the content1
It looks like the TOC can not index the location of the text and go to that part
Take my post as an example
![image](https://user-images.githubusercontent.com/60838786/170931244-f0c5af6b-21f9-4ed6-9012-d80a375979df.png)
My title start by 1.xxx 2.xxx
But it can not locate in certain part of the page if I click this TOC

If I use other content like the title [Introduction] (which number is not start in the first place), it will work~

**Comment by NYH-Dolphin** [comment]
Plus, you can see my website page to find this problem~
https://nyh-dolphin.github.io/games/unity-mirror/

**Comment by 526avijitgupta** [comment]
Hi @NYH-Dolphin Thanks for reporting this! My guess is the bug happens because the list is ordered

We'll push a fix for ordered list, but in the meantime could you please use `ordered = false` in your `config.toml` if that suits your case?

**Comment by yashmehrotra** [comment]
@NYH-Dolphin We have pushed a fix for this, please let us know if your issue has been resolved.
